// ChipotleDriver class declaration 

// main method declaration 

// fill in the blank spots below:

public class ChipotleDriver {
    public static void main(String[] args) {
        // Create a default Burrito
        Burrito defaultBurrito = new Burrito();

        // veggieBurrito: regular, veggie, white rice, pinto beans, guacamole, lettuce, tomatillo 
        Burrito veggieBurrito = new Burrito("Regular", "Veggie", "White Rice", "Pinto Beans", true, false, false, false, true);

        //copy of veggieBurrito with copy constructor
        Burrito veggieBurrito2 = new Burrito(veggieBurrito);

        //copy of defaultBurrito with copy constructor
        Burrito defaultBurrito2 = new Burrito(defaultBurrito);

        // 3 order of burrito
        BurritoOrder order = new BurritoOrder(3);
        
// **no need to change anything here**

// add defaultBurrito to the order
System.out.println(order.addBurrito(defaultBurrito));

// add veggieBurrito to the order
System.out.println(order.addBurrito(veggieBurrito));

// add veggieBurrito2 to the order
System.out.println(order.addBurrito(veggieBurrito2));

// add defaultBurrito2 to the order – what happens here? 
System.out.println(order.addBurrito(defaultBurrito2));

// are veggieBurrito and veggieBurrito2 the same? should be!
System.out.print("are veggieBurrito and veggieBurrito2 the same? ");
System.out.println(veggieBurrito.equals(veggieBurrito2));
// are veggieBurrito and defaultBurrito the same? shouldn't be...
System.out.print("are veggieBurrito and defaultBurrito the same? ");
System.out.println(veggieBurrito.equals(defaultBurrito));

// Should call order’s toString methods
System.out.println(order);